### ISSUE TITLE
PDF image one is not flipped

### ISSUE THREAD

**Issue by the-warby** [baldrick1/Videx-Soft-Switch-Clone#1]
If someone were to print the PDF and transfer it, the images wouldn't align because page one wasn't flipped but page two was.

**Comment by baldrick1** [comment]
But you can simply flip the transparency, vellum or paper over.

**Comment by the-warby** [comment]
yes, understood but I'm doing the iron on method so that doesn't work for me. But I will flip it before printing.

**Comment by the-warby** [comment]
thanks for sharing this BTW!
