### ISSUE TITLE
Issue when sending boards to print fab

### ISSUE THREAD

**Issue by Verault** [baldrick1/Videx-Soft-Switch-Clone#2]
I have tried to send these boards to print fab but they keep coming back rejected because of "Lack of the Soldermask layer."
![0020154946083](https://user-images.githubusercontent.com/64697404/231526417-d90801b9-678b-4cb9-b6dd-54c5b8f36129.png)

Is this something missing from the actual gerbers?

**Comment by baldrick1** [comment]
There is no solder mask layer.  This project was not ever intended for mass-production.

**Comment by Verault** [comment]
I understand that. Would this be something that can be easily added? I would like to have boards printed because whenever I find a Videx card in the wild( either clone or actual VIDEX)  they almost never have the softswitch and it would be great to remedy that. And whenever you see one come up for sale they are asking far too much. I would rather make my own.  I was assuming thats why the project was made.
________________________________

**Comment by baldrick1** [comment]
I will endeavour to do that and post it as an update.  Give me a day or two.
Note also, this is not a direct copy.  The circuit matches, but the parts layout differs.

**Comment by Verault** [comment]
Understood. And thank you. I will consult the BOM.

**Comment by baldrick1** [comment]
Added an updated gerber zip file.  I think the soldermask is on it.  Please check.

**Comment by Verault** [comment]
Success! Thank you for taking the time to do this!

**Comment by baldrick1** [comment]
If you order boards from PCBWay, mail me one -  I'll pay you for it.  
I'd love to see it and test it here.  I am "baldrick" on apple fritter dot com.  We can chat there if you'd like.
